"""Run the AI service with the deterministic scripted provider (integration testing only).

    python -m tests.run_stub_server --port 8000

This lets the full stack (frontend → backend → AI service → vector store) be exercised
end to end without a model. Responses are canned and NOT produced by an AI model; the
service reports provider "scripted-test" in /health so it can never be mistaken for one.
It is not reachable through application configuration.
"""
from __future__ import annotations

import argparse
import copy
import itertools

import uvicorn

from app.core.config import Settings
from app.core.container import build_container
from app.main import create_app
from app.providers.hashing_embedder import HashingEmbedder
from tests.stub_provider import QUESTION_JSON, ScriptedProvider, default_router

TOPICS = ["Deadlocks", "Indexing", "HTTP caching", "React hooks", "Event loop", "Sharding", "Normalization", "Closures"]


def make_router():
    counter = itertools.count(1)

    def router(prompt: str):
        result = default_router(prompt)
        if result is QUESTION_JSON:
            n = next(counter)
            topic = TOPICS[(n - 1) % len(TOPICS)]
            q = copy.deepcopy(QUESTION_JSON)
            q["question"] = f"[scripted #{n}] Explain {topic.lower()} and a trade-off you would consider in production."
            q["topic"] = topic
            return q
        return result

    return router


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--vector-db", default="./data/stub_vector_db")
    args = parser.parse_args()
    settings = Settings(
        environment="development", vector_store="chroma", vector_db_path=args.vector_db, embedding_provider="hash", rag_bootstrap_dir=""
    )
    provider = ScriptedProvider(router=make_router())
    container = build_container(settings, provider=provider, embedder=HashingEmbedder(settings.hash_embedding_dim))
    print("*** SCRIPTED TEST PROVIDER — responses are canned, NOT generated by an AI model ***")
    uvicorn.run(create_app(settings, container), host="127.0.0.1", port=args.port)


if __name__ == "__main__":
    main()
